### ISSUE TITLE
[BUG] players moving in jump animation in a stun/nova

### ISSUE THREAD

**Issue by SimonBpvp** [ClassicWoWCommunity/cata-classic-bugs#1051]
#### 1.1. 
when you stun someone in jump animation the jump trajectory continues
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. jump
           2. get stunned
           3. see where you land}
  #### 1.3  Source Material
(https://clips.twitch.tv/DeafTrappedSashimiSaltBae-afnsv0B92o-b8q3-)

#### 2.1. Description
the jump trajectory should end where the stun hits
  #### 2.2 Source Material
https://youtu.be/CJhu-n0UXyc?feature=shared&t=256
khuna stuns the priest and the priest drops from the jump straight down

**Comment by SimonBpvp** [comment]
also the exact same goes for novas
jumping in nova on beta: https://clips.twitch.tv/ObliqueCrazyShallotKappaRoss-4uqtRIhYwlirq5RN
and on retail it canceled the jump: https://youtu.be/rtHkvwwHBZA?feature=shared&t=339

**Comment by SimonBpvp** [comment]
this is still bugged and it affects PVP quite a bit, FIX PLEASE

**Comment by Artemishowl** [comment]
Ticketing, thank you!

**Comment by SimonBpvp** [comment]
This is fixed now!
