### ISSUE TITLE
[BUG] Shard of Woe only discounts 205 to all spells, instead of 405 to Holy/Nature spells and 205 to all other schools

### ISSUE THREAD

**Issue by Kangamooster** [ClassicWoWCommunity/cata-classic-bugs#1178]
#### 1.1. Description
Shard of Woe is currently only discounting all spells by 205 mana, including Holy and Nature spells.

  #### 1.2. How to Reproduce
           1. Check spell mana costs on tooltip
           2. Equip Shard of Woe
           3. Check mana cost again on the same spell
  #### 1.3  Source Material
https://github.com/JamminL/cata-classic-bugs/assets/166673485/4707cc59-d41f-4498-b55f-993c1454ff9f

#### 2.1. Description
In a hotfix shortly after patch 4.0.3, Shard of Woe was changed to reduce the base mana cost of all spells by 205 with the EXCEPTION of Holy and Nature spells, which were supposed to still be reduced by 405.

  #### 2.2 Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/166673485/f8ec63ef-7b62-4d06-adc7-b1350b6fe3f1)

**Comment by Loregon** [comment]
This situation is one of many examples of hidden nerfs of the distant past
https://www.mmo-champion.com/threads/991915-Shard-of-Woe-PTR-Nerf
https://www.mmo-champion.com/threads/992161-Shard-of-Woe-4-3-PTR-nerf
Blizz will not change the balance of items
