### ISSUE TITLE
[BUG] [live realms] I can't remove abilites from my pet bar

### ISSUE THREAD

**Issue by SimonBpvp** [ClassicWoWCommunity/cata-classic-bugs#1275]
#### 1.1. Description
I can't remove any button from off my pet bar, if I want my pet bar to be clean and empty I can't do it
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. drag a button from the pet bar
           2. try to put it into the floor
           3. it stays on the pet bar

this only applies to Stay, Moveto, Assist, Defensive, Passive, Attack. 
it does NOT apply to spells like Shadow Bite. Those can be moved as normal and are not bugged

**Comment by Calzeru** [comment]
Can confirm. I dragged "Move to" from the pet spellbook to my pet bar, but accidentally replaced Huddle (dk ghoul ability) instead of Defensive. Now I can't get Huddle back on the bar..

**Comment by SimonBpvp** [comment]
this is completely fixed for me. Fixed?

**Comment by Calzeru** [comment]
Yeah, works for me too now!
