### ISSUE TITLE
[BUG] Character Panel Mastery Tooltip has a misplaced %

### ISSUE THREAD

**Issue by Tharre** [ClassicWoWCommunity/cata-classic-bugs#1340]
#### 1.1. Description

The tooltip says "Mastery: 574 [+12.50%]" where it should be "Mastery: 574 [+12.50]" (no %) since these are mastery points and not percentages.

  #### 1.2. How to Reproduce
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/2140018/2d1868a5-43e7-47c5-b507-67d4089591d1)
#### 2.1. Description
The tooltip should not have a `%` at the end. Normally this would be a very minor bug, but combined with the fact that mastery  for some specs is rounded down to full percentage points NOT to mastery points (see #1256) this confuses very many people.

  #### 2.2 Source Material
https://www.youtube.com/watch?v=JF-Gqd0lxm4&t=204s

**Comment by AidanZMoon** [comment]
We are aware of this.

There is also a % next to your expertise points that should not be there on the character sheet.
Low priority.

**Comment by raethkcj** [comment]
Fixed in 4.4.1
![image](https://github.com/user-attachments/assets/6820ac7b-a16c-4595-afd5-19129aa375c2)
