### ISSUE TITLE
[BUG] Many Firelands weapons are missing their damage ranges

### ISSUE THREAD

**Issue by raethkcj** [ClassicWoWCommunity/cata-classic-bugs#1400]
#### 1.1. Description
  The following items have a Min and Max Damage of 0, causing them to have no visible damage range or DPS value in-game:
  https://wago.tools/db2/ItemSparse?build=4.4.0.55006&filter[InventoryType]=13%7C15%7C17%7C21%7C25%7C26&filter[MinDamage_0]=exact%3A0&filter[MinDamage_1]=exact%3A0&filter[OverallQualityID]=%3C7&filter[Bonding]=1&page=1&sort[Display_lang]=asc
  
  They appear to all be from the Firelands raid, other than `71713` which is presumably a test item.
  #### 1.2. How to Reproduce
1. Link any of the affected items in-game, e.g.:
           `/script DEFAULT_CHAT_FRAME:AddMessage("\124cffa335ee\124Hitem:71409::::::::85:::::\124h[Funeral Pyre]\124h\124r")`
2. View the tooltip and observe it has no damage

  #### 1.3  Source Material
 
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/ac69b565-b479-4d3d-8a0e-200c2f29e39b)

#### 2.1. Description
  All of these weapons should have nonzero damage ranges.
  #### 2.2 Source Material
  E.g. https://warcraft.wiki.gg/index.php?title=Funeral_Pyre&oldid=231233

**Comment by Artemishowl** [comment]
Ticket created

**Comment by zoristaken** [comment]
> Similarly, it looks like quite a few Firelands items currently have 0 Armor. I have no idea if this is an exhaustive list, but it looks like primarily Firelands body armor:
> 
> [https://wago.tools/db2/ItemSparse?build=4.4.0.55006&filter[InventoryType]=1|3|5|6|7|8|9|10|14|16|20&filter[OverallQualityID]=exact%3A4&filter[Bonding]=1&filter[Resistances_0]=exact%3A0](https://wago.tools/db2/ItemSparse?build=4.4.0.55006&filter%5BInventoryType%5D=1%7C3%7C5%7C6%7C7%7C8%7C9%7C10%7C14%7C16%7C20&filter%5BOverallQualityID%5D=exact%3A4&filter%5BBonding%5D=1&filter%5BResistances_0%5D=exact%3A0)

This is still an issue on the latest patch

**Comment by raethkcj** [comment]
Hotfixed on PTR!
