### ISSUE TITLE
[BUG] Unable to complete the achievement:  "Loremaster of Kalimdor"

### ISSUE THREAD

**Issue by Critshappen** [ClassicWoWCommunity/cata-classic-bugs#1417]
### 1. Current Behavior
The "Loremaster of Kalimdor" meta achievement doesn't recognize some completed achievements as completed for the meta.
  #### 1.1. Description
All Kalimdor quest achievements completed, but the "Loremaster of Kalimdor" meta achievement do not recognize some of them as completed.
  #### 1.3  Source Material
  ![image_2024-06-18_214245477](https://github.com/JamminL/cata-classic-bugs/assets/100601364/a2910f23-5a57-4c42-860e-da318135aef2)
![image_2024-06-18_214320933](https://github.com/JamminL/cata-classic-bugs/assets/100601364/419a4b3d-28c7-418f-b266-7ed43762189d)
![image_2024-06-18_214336491](https://github.com/JamminL/cata-classic-bugs/assets/100601364/098b2114-2bb6-43f6-a54f-9bbdcfef0dda)
![image_2024-06-18_214354032](https://github.com/JamminL/cata-classic-bugs/assets/100601364/083c24c9-89da-4529-9fcf-52615c2cb409)
![image_2024-06-18_214407261](https://github.com/JamminL/cata-classic-bugs/assets/100601364/a8d698ee-75e6-42c0-9c69-ffda84ee73e5)

**Comment by ojoemichi** [comment]
I have the same problem. You already fix it?

**Comment by Artemishowl** [comment]
Ticket created

**Comment by Critshappen** [comment]
This has been fixed.
