### ISSUE TITLE
[BUG] exhaustion / sated doesn't reset on death

### ISSUE THREAD

**Issue by SimonBpvp** [ClassicWoWCommunity/cata-classic-bugs#1430]
#### 1.1. Description
the Bloodlust / Heroism debuff doesn't reset on death. Time warp still resets on death as normal. Only shaman version is bugged
  #### 1.2. How to Reproduce

           1. lust
           2. kill the player
           3. res
  #### 1.3  Source Material
https://clips.twitch.tv/AntediluvianApatheticHamburgerRiPepperonis-Yw9VSgW3eLxDerN0
#### 2.1. Description
dying should clear these debuffs

  #### 2.2 Source Material
https://www.wowhead.com/cata/spell=57724/sated
<img width="1014" alt="Screenshot 2024-06-23 at 02 16 25" src="https://github.com/JamminL/cata-classic-bugs/assets/94299191/91251eb4-6113-437b-a9b7-8345a847a990">

**Comment by AidanZMoon** [comment]
This a bug, but it's bugged but in the opposite way.

Time Warp's debuff should not go away when you die.

This protection was put in place in wrath classic when cooldowns were made to reset on encounter end. OG Cataclysm and OG Wrath did not have a cooldown reset to my knowledge. T14 5.0 was when it first came in for long cooldowns (could be wrong?).

So this is to prevent you doing a fight, dying during an intermission on purpose, taking a soul stone/reincarne and then getting a second lust in the fight.

**Comment by SimonBpvp** [comment]
Cool, I will just say first I think you are not correct about how it worked on original cata, below is a clip of someone dying on Ultraxion HC, and he loses the buff. 
HOWEVER, as you say in 2024 with parses and everything, you should probably do whatever you think is best with something like Heroism, as long as you make it consistent between mage version and shaman version of course. I would be reasonably happy with the different approach that you refer to and I think it would be justifiable. Although it does affect RBG games a bit but imagine caring about RBGs in 2024.

Ultraxion HC:
https://www.youtube.com/watch?v=Rr4YyKaU7Ik&t=357s

RBGs:
https://youtu.be/CIIkgd7juWo?feature=shared&t=162

**Comment by AidanZMoon** [comment]
I'm not correct about how it worked in Original Cataclysm?

My impression is in OG Cata if you died you lost all types of sated/exhausted etc.
But OG Cata did not have Cooldown reset on Encounter_End in PvE.

Is this incorrect?

**Comment by SimonBpvp** [comment]
You're completely correct there, I think I have misunderstood you, sorry. Now I understand.

Will it be that the buff persists through death in classic then?

**Comment by SimonBpvp** [comment]
I'll just note that in RBGs the bloodlust is a very important buff for team fights, and a key element in RBG games was always to pop a second bloodlust after you wiped. This gives the losing team an advantage when you can have lust in 2 consecutive fights and it's usually the only thing that allows you to retake for example Waterworks after you lose the first fight. That was the thinking behind of my original report, that right now only Time Warp is letting you do this.

**Comment by SimonBpvp** [comment]
the change is live I think.
