### ISSUE TITLE
[BUG] Vanilla PvP gear cannot be transmogged at all

### ISSUE THREAD

**Issue by Kolmarwow** [ClassicWoWCommunity/cata-classic-bugs#1437]
#### 1.1. Description
In original Cataclysm, Vanilla PvP gear was untransmoggable & replaced with Replica versions sold by various vendors in Netherstorm for transmog purposes. You had to get rank 8+ in original Vanilla to gain access to these vendors, tracked through feat of strength achievements.

For Cataclysm Classic, Blizzard announced in a [blue post](https://us.forums.blizzard.com/en/wow/t/cataclysm-classic-launch-notes-updated-june-4/1856207#pvp-item-transmogs-5) that they would not be doing this, instead making the original gear transmoggable & available from honor vendors.

However it seems like they forgot to implement this, the gear can be bought but it does not get added into your transmog collection. As far as I know the Replica versions aren't available either even if you meet the rank 8+ requirement, so it's currently impossible to transmog Vanilla PvP gear.

#### 2.1. Description
Vanilla PvP gear should be available for transmogging, as stated in Blizzard's blue post.

**Comment by Zereges** [comment]
You need new ranks from ranked BGs for them to be added to the collection tab (i.e. [Master Sergeant](https://www.wowhead.com/cata/achievement=5333) (alliance))

**Comment by Kolmarwow** [comment]
That was something that Blizzard added in Mists of Pandaria which doesn't apply to Cata Classic afaik, but I don't know for sure as I have neither the feat of strength nor the RBG rank to test. Would be good if someone with those can confirm, I've not found any post that shows someone with the transmogged gear yet.

Interestingly while searching I found this [Blizzard support article](https://us.battle.net/support/en/article/10702) that has a section for Cata Classic at the bottom, saying "These items are currently not available for transmogrification and the NPCs are not in the game either". Looks like Blizzard is aware of the problem at least.

**Comment by Zereges** [comment]
This should be a proof that legacy achiev doesn't work. I don't have a Rated BG rating so can't test that.

![image](https://github.com/JamminL/cata-classic-bugs/assets/7399594/191ff63c-89c3-4375-ad42-9d500a37d392)

**Comment by Kolmarwow** [comment]
This has been fixed, the gear bought from honor vendors can now be transmogged.

**Comment by Zereges** [comment]
This is mostly fixed, although I cannot get the Grand Marshal items to be marked as collected as apparently the weapons are not in the appearances tab at all
![image](https://github.com/user-attachments/assets/d6ad0f63-ba66-4ec4-ab94-a2692520574a)
