### ISSUE TITLE
[BUG] pet bar is locked in wrong spot (new bug)

### ISSUE THREAD

**Issue by SimonBpvp** [ClassicWoWCommunity/cata-classic-bugs#1449]
#### 1.1. Description
my pet bar is hidden behind action bar 2 on my warlock. I have to MoveAny it as a workaround.
  #### 1.2. How to Reproduce

           1. summon a demon

  #### 1.3  Source Material
this is with default UI and all addons disabled
![image](https://github.com/ClassicWoWCommunity/cata-classic-bugs/assets/94299191/8c24d793-fdeb-4960-91f9-9aac889258c9)
![image](https://github.com/ClassicWoWCommunity/cata-classic-bugs/assets/94299191/7ac1088f-67b6-415d-99fd-8004ee025b01)

you can see it's there hidden behind the bar.
#### 2.1. Description
it should be revealed
  #### 2.2 Source Material
![image](https://github.com/ClassicWoWCommunity/cata-classic-bugs/assets/94299191/7baf235b-f56f-47bf-af1a-5e9ec94b3294)

**Comment by Kinlyo** [comment]
same thing here. pet bar suddenly went behind actionbar2 / actionbar3 and got stuck there.
the bug persists across characters with pets.
![image](https://github.com/ClassicWoWCommunity/cata-classic-bugs/assets/175112134/b3b5e1db-bc96-4a67-9ed9-76fae4dfdb73)
![image](https://github.com/ClassicWoWCommunity/cata-classic-bugs/assets/175112134/bcd4b803-bead-4402-b9a0-dfbde4886d8d)

**Comment by SimonBpvp** [comment]
you probably need the addon MoveAny untill they fix it
