### ISSUE TITLE
[BUG] Target of Target HP doesn't work

### ISSUE THREAD

**Issue by SimonBpvp** [ClassicWoWCommunity/cata-classic-bugs#1459]
#### 1.1. Description
the unit frame Target of Target doesn't update the green HP bar for me. It only updates once the player switches targets, but otherwise it doesn't update.
  #### 1.2. How to Reproduce
           1. in duel maybe?

in this clip look at my focus ToT, (its possible that this bug only affects focus frame, but I think it affects target frame too)
https://streamable.com/sdin52
#### 2.1. Description
the ToT frame should update HP bar in real time
  #### 2.2 Source Material

**Comment by JamminL** [comment]
Duplicate of #579
