### ISSUE TITLE
[BUG] Hurricane weapon enchant has ICD

### ISSUE THREAD

**Issue by SimonBpvp** [ClassicWoWCommunity/cata-classic-bugs#1460]
#### 1.1. Description
at the moment it has an ICD of 45 seconds just like Power Torrent, which makes it slightly underpowered.
  #### 1.2. How to Reproduce
        
           1.    enchant hurricane on wep
           2.   hit dummy     
           3.   time the procs to check ICD
  #### 1.3  Source Material

#### 2.1. Description
its supposed to have no ICD
  #### 2.2 Source Material
https://www.wowhead.com/cata/spell=74223/enchant-weapon-hurricane#comments
https://www.wowhead.com/cata/item=52760/enchant-weapon-hurricane#comments

**Comment by CharWS** [comment]
were you testing with spells or melee attacks?

**Comment by SimonBpvp** [comment]
spells only, fire mage

**Comment by CharWS** [comment]
then that's normal, if you read through the other comments you'll see that the icd was only removed for melee attacks but is still there for spells
