### ISSUE TITLE
[BUG] Brain Freeze does not benefit from Fingers of Frost

### ISSUE THREAD

**Issue by TheHate123** [ClassicWoWCommunity/cata-classic-bugs#1469]
#### 1.1. Description
Currently, if you use a Frostfire Bolt when you have both Brain Freeze and Fingers of Frost up, it will consume both, but it will not benefit from Fingers of Frost's increased crit chance via Shatter.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Get Fingers of Frost and Brain Freeze up at the same time multiple times, ideally with high crit on gear, would be perfect if above 33.34% (this guarantees that your Frostfire Bolt is supposed to have 100% crit everytime with both procs, as 33.34% x 3 (Shatter's multiplier) = 100.00%.
           2. Throw some Frostfire Bolts this way and observe how they don't actually have 100% crit.
  #### 1.3  Source Material
https://www.youtube.com/watch?v=JkaBonSCPYw - My crit in the video after a dozen or so Frostfire Bolts is somewhere around 30%, which is my base crit as you can see on the character sheet.
#### 2.1. Description
The tooltip of the talent itself states that it should benefit. Also Kuni's guide from retail back in the day has info on this.
  #### 2.2 Source Material
https://www.wowhead.com/cata/spell=44549/brain-freeze - Tooltip states "When Frostfire Bolt is instant, it can benefit from **Fingers of Frost**".
https://www.mmo-champion.com/threads/813785-Kuni-s-Frost-Mage-PVE-Guide-(Cataclysm) - Kuni's MMO-champion guide.
https://youtu.be/2pqY1t8pf08?si=SMKxB_k86G4de5ed&t=293 - This guy was non-stop critting with his Frostfire Bolts after the first one. Even early on, the ratio is 7-1, clearly benefit from Shatter. By the end it's upwards of 20 crits.
The old simcraft, version 4.3, also shows 100% crit on Frostfire Bolt, assuming 33.34% crit for the player and with a line to only cast Frostfire Bolt under both Brain Freeze and Fingers of Frost.

**Comment by kenthklui** [comment]
Confirming this bug report: I was able to put together a gearset with 33.36% crit, but Frostfire Bolt casted under Fingers of Frost does not guarantee a crit.

![image](https://github.com/user-attachments/assets/f726b2d2-09c3-43dd-8be5-cb9c7931323a)
![image](https://github.com/user-attachments/assets/77a99788-8ca4-4808-8ab0-f5a022c4a188)

**Comment by espionn** [comment]
> Confirming this bug report: I was able to put together a gearset with 33.36% crit, but Frostfire Bolt casted under Fingers of Frost does not guarantee a crit.
> 
> ![image](https://private-user-images.githubusercontent.com/1038272/353988503-f726b2d2-09c3-43dd-8be5-cb9c7931323a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NTk4NzAsIm5iZiI6MTcyMjU1OTU3MCwicGF0aCI6Ii8xMDM4MjcyLzM1Mzk4ODUwMy1mNzI2YjJkMi0wOWMzLTQzZGQtOGJlNS1jYjljNzkzMTMyM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDA0NjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjAxMTY2OGMxYTcxM2YyMzdiYTU1ZDc4Y2Y3ZTQxZGNkOTZhNGYwNTU2ZjIyZmI1MWE4OTM4NTlhYWFkY2M0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T4cd8SYRp6p2jrguP68_kCpPKX95eifu_fM_S5tiWWw) ![image](https://private-user-images.githubusercontent.com/1038272/353988599-77a99788-8ca4-4808-8ab0-f5a022c4a188.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NTk4NzAsIm5iZiI6MTcyMjU1OTU3MCwicGF0aCI6Ii8xMDM4MjcyLzM1Mzk4ODU5OS03N2E5OTc4OC04Y2E0LTQ4MDgtOGFiMC1mNWEwMjJjNGExODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDA0NjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzJlOWRjODhjODdhN2RmODJiN2Q0MDFmMDg4YzExYTA4YjI0NmUzMDI2NzI2NTBlM2QyNmQ2ZWY3ODhkNzI0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T5MoopTcPWQfSC9-2MwsYb042i-eWaXNH_dWxxHr88Q)

Not that I doubt this is indeed bugged, but is this methodology sound? I would've thought the Raider's Training Dummy had crit suppression as a boss lvl mob.

**Comment by kenthklui** [comment]
> > Confirming this bug report: I was able to put together a gearset with 33.36% crit, but Frostfire Bolt casted under Fingers of Frost does not guarantee a crit.
> > ![image](https://private-user-images.githubusercontent.com/1038272/353988503-f726b2d2-09c3-43dd-8be5-cb9c7931323a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NTk4NzAsIm5iZiI6MTcyMjU1OTU3MCwicGF0aCI6Ii8xMDM4MjcyLzM1Mzk4ODUwMy1mNzI2YjJkMi0wOWMzLTQzZGQtOGJlNS1jYjljNzkzMTMyM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDA0NjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjAxMTY2OGMxYTcxM2YyMzdiYTU1ZDc4Y2Y3ZTQxZGNkOTZhNGYwNTU2ZjIyZmI1MWE4OTM4NTlhYWFkY2M0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T4cd8SYRp6p2jrguP68_kCpPKX95eifu_fM_S5tiWWw) ![image](https://private-user-images.githubusercontent.com/1038272/353988599-77a99788-8ca4-4808-8ab0-f5a022c4a188.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NTk4NzAsIm5iZiI6MTcyMjU1OTU3MCwicGF0aCI6Ii8xMDM4MjcyLzM1Mzk4ODU5OS03N2E5OTc4OC04Y2E0LTQ4MDgtOGFiMC1mNWEwMjJjNGExODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDA0NjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzJlOWRjODhjODdhN2RmODJiN2Q0MDFmMDg4YzExYTA4YjI0NmUzMDI2NzI2NTBlM2QyNmQ2ZWY3ODhkNzI0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T5MoopTcPWQfSC9-2MwsYb042i-eWaXNH_dWxxHr88Q)
> 
> Not that I doubt this is indeed bugged, but is this methodology sound? I would've thought the Raider's Training Dummy had crit suppression as a boss lvl mob.

This is indeed the case and I should have tested on a regular (ie. 85) dummy instead.

**Comment by NBEM** [comment]
I also found this bugged today, but my testing* showed some interesting additional caveats:
- Frostfire Bolt was benefitting from Fingers of Frost because it was clearly getting the damage boost from the Frostburn Mastery. It seems to be Shatter that's not benefitting 
- Removing the Glyph of Frostfire actually fixed this, which points it as the potential culprit.

*Testing involved two ~10 minute sessions of Frost rotation (minus Ice Lance and Deep Freeze to keep Finger stacks exclusively for Frostfire Bolt) against a raid dummy with a 22.6% crit chance character. Results were:
- No Glyph; 40 Frostfire Bolts, 29 criticals (72.5% rate)
- With Glyph; 35 Frostfire Bolts, 11 criticals (31.4% rate)

**Comment by laynerzy** [comment]
Still not fixed

**Comment by Kethryllia** [comment]
Can you all retest in 4.4.1? Admittedly, this wasn't on a character with 16.74% base spell crit, but I equipped the Glyph of Frostfire Bolt, and then cast Frostfire Bolt against a target that was both frozen and unfrozen.

Unfrozen target crit chance: 16.7389%
Frozen target crit chance: 50.2168%

I then unequipped the glyph. Here are the respective FFB crit chances without the glyph:
Unfrozen: 16.7389%
Frozen: 50.2168

I then procced Brain Freeze and Fingers of Frost with the glyph slotted, and Frostfire Bolt's crit chance was 50.2168.

Either I'm missing something, or this seems to be good to me.

**Comment by laynerzy** [comment]
Hello, the issue was about fingers of frost while using the FFB glyph, frostfire bolt crits normally on frozen (root'd/deep frozen) targets, i just tested it again with way over 33% crit (crit capped), and my FFB did not crit everytime.
Once removing the frostfire bolt glyph my crit chance was 100%.

**Comment by Kethryllia** [comment]
Hm, I'm honestly not sure how that differs from what I tested? I got the crit increase when I'd procced Fingers of Frost and Brain Freeze; that was the last test that I listed:

"I then procced Brain Freeze and Fingers of Frost with the glyph slotted, and Frostfire Bolt's crit chance was 50.2168."

Can you provide your character name and realm so that I can try it in a more real world circumstance?

**Comment by laynerzy** [comment]
laynerz-firemaw

**Comment by laynerzy** [comment]
Here is a recording i just took, as you can see while crit capped on my frostfire bolt (100% crit chance) i only crit 1 out of 4 frostfire bolts, then after removing the frostfire bolt glyph i crit every single one. i have tested this several times
https://www.youtube.com/watch?v=k-FdNXILyyQ

**Comment by Kethryllia** [comment]
Repro found and bug reopened. Thanks so much for the diligence!

**Comment by Kethryllia** [comment]
This should now be resolved.
