### ISSUE TITLE
[BUG] garrote not reapplying the dot

### ISSUE THREAD

**Issue by SimonBpvp** [ClassicWoWCommunity/cata-classic-bugs#1481]
#### 1.1. Description
When you reapply garrote with a less powerful garrote, it won't re-apply. I think this is because of the "more powerful spell already active" mechanic.
  #### 1.2. How to Reproduce

           1. pop on use and do a big garrote on target dummy
           2. cancel your procs then do a smaller garrote
           3. check the dot
  #### 1.3  Source Material
target dummy:
https://streamable.com/bsyoix
arena game:
https://gyazo.com/9086e13f611ded8412c375d60e659e7a
#### 2.1. Description
I'm guessing it should allow you to refresh garrote but i don't know for sure.

Also there are other dot refreshing mechanics which are bugged right now and I wonder if they aren't all related to this more powerful spell already active mechanic, or perhaps some completely different fix which has downstream effects on dots. Or this garrote thing could be a totally independent thing on it's own.

quick list of potentially related issues:
#1376, #1394, #1354, #985, #872

**Comment by Artemishowl** [comment]
Unsure if bug, moving to review for QA to check.

**Comment by SimonBpvp** [comment]
I found a clip that supports this not being a bug and being accurate:
neilyo garrotes the warlock twice, the 2nd time there is no bleed. Notice the agility buff totem goes away before the 2nd garrote. 
https://youtu.be/uvRoBbnQuII?feature=shared&t=315

I'm thinking not a bug.
