### ISSUE TITLE
[BUG] Mount Hyjal NPCs kill me when porting in

### ISSUE THREAD

**Issue by ChristianBlom84** [ClassicWoWCommunity/cata-classic-bugs#1484]
#### 1.1. Description
           Furious Mount Hyjal Wardens run over and one-shot me when I port in.
  #### 1.2. How to Reproduce
           Take the portal to Mount Hyjal
#### 2.1. Description
           I should not be killed by the NPCs.

I'm friendly with Guardians of Hyjal, so that's not it. This looked kind of fixed for a while, but now it happened again.

**Comment by ssabbyccatt** [comment]
This has been reported previously. It's not just Mt Hyjal, it's any neutral npc. See: https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/1113

**Comment by ChristianBlom84** [comment]
Issue number 1113 of thousands not fixed. Feels kinda pointless to even report anything since they don't give a shit about Cata classic anyway. Oh well.

**Comment by raethkcj** [comment]
Duplicate of #1113
