### ISSUE TITLE
[BUG] Insect Swarm's tooltip incorrectly states it does only nature damage

### ISSUE THREAD

**Issue by ssabbyccatt** [ClassicWoWCommunity/cata-classic-bugs#1487]
#### 1.1. Description
Insect Swarm's tooltip still states that it does only nature damage.
  #### 1.2. How to Reproduce
           1. Open spell book & read tooltip
  #### 1.3  Source Material
https://www.wowhead.com/cata/spell=5570/insect-swarm
#### 2.1. Description
Insect Swarm was changed to do nature+arcane damage, so its tooltip should be updated. This is extremely inconsequential, but since it hasn't been updated on PTR I wanted to go ahead and submit a report on this. 
  #### 2.2 Source Material
https://www.wowhead.com/blue-tracker/topic/us/balance-druid-changes-1875457

**Comment by Kethryllia** [comment]
I've checked our reference client, and it only states that Insect Swarm does Nature damage. I checked the 4.3.4 data, and both it and the 4.4.X version of Insect Swarm have it set to do Nature and Arcane.

While the tooltip is inaccurate, it's an inaccuracy carried over from original Cataclysm and doesn't impact the spell's functionality, so we won't be bugging it at this time.

Thanks for the report!
