### ISSUE TITLE
[BUG][FIRELANDS] Rings of fire don't spawn on stage two of Alysrazor

### ISSUE THREAD

**Issue by dccdcd** [ClassicWoWCommunity/cata-classic-bugs#1493]
#### 1.1. Description
During stage two of Alysrazor rings of flame do not spawn alongside the fiery tornados.
  #### 1.2. How to Reproduce
           1. Pull alysrazor
           2. Wait until stage two
           3. Look for rings of fire
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
Rings of fire should spawn throughout the arena on the ground during this phase, allowing flyers from stage one to keep up their stacks of burning power.
  #### 2.2 Source Material
[The warlock runs through rings of fire during stage two](https://youtu.be/-OvtP7TTt0k?feature=shared&t=307)

**Comment by Beakachu** [comment]
Fixed.
