### ISSUE TITLE
[BUG] Knock Back spells (Thunderstorm, Typhoon) have no effect

### ISSUE THREAD

**Issue by dccdcd** [ClassicWoWCommunity/cata-classic-bugs#1494]
#### 1.1. Description
Using any knockback (typhoon, thunderstorm) on Sons of Flame during the intermission on Ragnaros has no effect on the mobs.
  #### 1.2. How to Reproduce
           1. Pull ragnaros
           2. Get him to intermission phase
           3. Cast a knockback on the sons of flame adds
#### 2.1. Description
Knockbacks should work on these mobs. They should only be immune to roots and slows.
  #### 2.2 Source Material
[2 boomkins knocking back the mobs one after eachother](https://youtube.com/clip/UgkxdMgQJod1jsbyk4LGB20O0BO1cb6akyyM?feature=shared)

**Comment by raethkcj** [comment]
This appears to be a bug with Knock Back effects in general; none of them knock enemies in any zone.
