### ISSUE TITLE
[#SomeChanges Suggestion][FIRELANDS] All NERF are included

### ISSUE THREAD

**Issue by Loregon** [ClassicWoWCommunity/cata-classic-bugs#1499]
### Description
I think everyone who has already tried the PTR noticed that, aside from the bugs, the version of the bosses in the 'Firelands' being offered is weakened and represents the final version from Patch 4.3. In the current state, the raid seems easier than in the first phase, although, of course, Ragnaros will still require some time to defeat.

In 2011, the developers significantly weakened the bosses a month before the release of Patch 4.3, which, theoretically, should have been a division between post-nerf progression and boss balancing. It weakened all bosses by 15-25%.

> Hotfixes Sep 20, 2011 11:00 AM PDT 
https://web.archive.org/web/20110923153100/http://us.battle.net/wow/en/blog/3019413

There was also another small hotfix for Ragnaros dated September 8.

> Ragnaros' health has been reduced by 15%, and the melee damage of molten elementals was reduced by about 25% on Heroic difficulty. 
https://wowpedia.fandom.com/wiki/Patch_4.2.2

Also, in 2011 there was an interesting blue post that described a developer mistake from back then regarding the Geyser mechanic during Ragnaros’ Phase 4. 

> https://www.bluetracker.gg/wow/topic/gb-en/3061856206-firelands-43-stealth-nerf/

So, if someone asked me which version I consider ideal, it would be Ragnaros and Firelands with the September 8 nerf but with the Geyser hitbox fixed so that it wouldn't allow the 3 camps strategy.

**Comment by NerdEgghead** [comment]
July 19th is the hotfix state I personally would like to see implemented for a Classic re-release. All the major mechanics bugs were fixed at that point, but the encounter tuning was not yet significantly nerfed.
