### ISSUE TITLE
[BUG][Firelands] Reactive Flame Tooltip Crashes Clients

### ISSUE THREAD

**Issue by Northlol** [ClassicWoWCommunity/cata-classic-bugs#1508]
#### 1.1. Description
Viewing the tooltip of Reactive Flame (domo trash) will sometimes cause client crashes
  #### 1.2. How to Reproduce
           1. Engage Druids of the Flame
           2. Damage them during reactive flame
           3. Navigate the in game cursor to the debuff
  #### 1.3  Source Material
![image](https://github.com/user-attachments/assets/7074ae88-c82c-4f7d-b64e-4b74f0926b74)
#### 2.1. Description
Tooltip should display properly without crashing the client.
  #### 2.2 Source Material
N/A

**Comment by Beakachu** [comment]
Fixed - you can close this.
