### ISSUE TITLE
[BUG] There is pathable water under the Molten Front zone

### ISSUE THREAD

**Issue by raethkcj** [ClassicWoWCommunity/cata-classic-bugs#1513]
#### 1.1. Description
  Between all the floating islands of the Molten Front, there is a layer of water under most of the zone, with pixelated holes. The water is swimmable and works with water walking.
  #### 1.2. How to Reproduce
           1. Go to the Molten Front
           2. Jump off the edge
  #### 1.3  Source Material
![image](https://github.com/user-attachments/assets/88bd6d42-f899-468e-b22f-7803aca651ff)

#### 2.1. Description
  Jumping off the edge should cause your character to fall into a kill zone.

**Comment by skyler-code** [comment]
![image](https://github.com/user-attachments/assets/0394baf4-1f79-4a54-8534-87e83e0fdd08)
Fixed in 4.4.1.56859
