### ISSUE TITLE
[BUG] Heroic 372 Tier 11 Head and Shoulder requires normal piece as well as heroic token

### ISSUE THREAD

**Issue by Beakachu** [ClassicWoWCommunity/cata-classic-bugs#1533]
#### 1.1. Description
After the Firelands patch, the tier 11 normal tokens for head and shoulder were added to the Fissure Stone vendor.
To purchase a heroic ilvl 372 head or shoulder, the justice point vendor is asking for the 359 piece as well as a heroic token.
Those pieces require 64 stones, so approx 6 dungeons so an additional 3-5 hour investment per character.

#### 2.1. Description
Like in phase 1 and 2, the heroic pieces should be purchasable with just the heroic token and not require the 359 piece as well.

  #### 2.2 Source Material
![Screenshot 2024-10-31 174228](https://github.com/user-attachments/assets/72b9faca-fe4c-4f78-b44c-b1ac56168beb)

**Comment by Kethryllia** [comment]
Right now, it's not entirely clear if this is intended or not, since this is consistent with our reference client but not 4.4.0. I have a bug in to see which cost design wants to go with in 4.4.1.

**Comment by ToN1c** [comment]
> Right now, it's not entirely clear if this is intended or not, since this is consistent with our reference client but not 4.4.0. I have a bug in to see which cost design wants to go with in 4.4.1.

Back then you could raid normal and heroic, now you would have to waste a id to optain the normal version.
Firelands tier head/shoulder only requires the heroic token because that how it should work in classic

**Comment by Beakachu** [comment]
This is fixed.
