### ISSUE TITLE
[BUG] cant /cancelaura divine aegis in combat

### ISSUE THREAD

**Issue by gekkuxz** [ClassicWoWCommunity/cata-classic-bugs#1539]
#### 1.1. Description
Divine Aegis buff cannot be removed by typing **/cancelaura divine aegis** while in combat, the only workaround is manually right clicking the buff
  #### 1.2. How to Reproduce
           1. cast prayer of healing while having divine aegis talent learned
           2. get in combat
           3. type /cancelaura divine aegis and notice it doesnt work
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
/cancelaura divine aegis should remove the buff divine aegis
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by NerdEgghead** [comment]
Decent chance it's the same bug as this:
https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/1214
