### ISSUE TITLE
[#SomeChanges Suggestion] webhook for repository to discord channel?

### ISSUE THREAD

**Issue by Brozee033** [ClassicWoWCommunity/cata-classic-bugs#1544]
### Description
Trying to get all issues to post automatically to our discord channel (like the dk discord channel does)

Installed the bot, but no access to do a webhook creation.  Is there any way to do this? channel referenced below.

https://discord.com/channels/894792866658930688/989249329430663238

**Comment by CharWS** [comment]
test
