### ISSUE TITLE
[BUG] Explosive Shot doesn't deal damage

### ISSUE THREAD

**Issue by RA80533** [ClassicWoWCommunity/cata-classic-bugs#1549]
#### 1.1. Description
Explosive Shot doesn't deal damage. It does not hit for its initial tick nor does it apply its dot effect.

#### 2.1. Description
It's supposed to deal damage and apply a dot effect.

**Comment by Kethryllia** [comment]
This is a caching issue; if you delete the client cache in your install folder, it clears up the problem: https://us.forums.blizzard.com/en/wow/t/explosive-shot-appears-to-be-bugged/2007134/4
