### ISSUE TITLE
[BUG] Dragonwrath, Tarecgosa's Rest questline - "Delegation" quest

### ISSUE THREAD

**Issue by Kyung783** [ClassicWoWCommunity/cata-classic-bugs#1552]
Currently there's a bug that if someone that already has Branch of Nordrassil opens the portal for another player in the questline they can't advance on the quest due to the npc "Tormented Protector" not interacting with the person that is still on that step and it just gets stuck there.

With the current buffed cadence of producing staffs this is struggle as every raid has to go through doing the quests every boss on normal difficulty, then wiping on purpose, go finish the quest and then finally clearing the raid on heroic.

Please, look into this,

Kind regards,
Players with a lot of characters

**Comment by Moistxx** [comment]
Agree with this. You should be able to open the portal from a character that has already progressed past this stage of the quest. It saves each raid at-least 30minutes per raid.

Combined with the increased drop chance on all the items, being able to speed this process up will greatly help all the guilds doing multiple runs. It also benefits all the guilds who even only do 1 raid as otherwise they will constantly be having to do this quest for each raider.

**Comment by NoCement** [comment]
Disclaimer: there is thin possibility that after this reset, it will work, that this quest can be done once per week on character (including summoning for someone else). But I doubt it.

As it works currently, it is huge issue. You can open the portal for other people but it is pointless, part where NPC morphs quest person into a Treant simply does not happen and and whole encounter resets after a while.

This is extremely bad with speed up progression, especially in 25 man. This mean every raid every week have to do Delegation quest.

Kindly requesting hotfix ASAP.

**Comment by HedvaCZ** [comment]
Adding a footage as evidence of this happening:
https://www.youtube.com/watch?v=LP4RVCY3r_A

**Comment by ssabbyccatt** [comment]
This bug has been partially fixed - https://us.forums.blizzard.com/en/wow/t/cataclysm-dragonwrath-foci-skip-doesnt-do-anything/2013035/8. 

Unfortunately, only the person who actually completed the foci 4-boss event can open the portal successfully and allow others to loot. If Person A (who did the 4-boss event) opens the portal for Person B, then Person B (who skipped the event via Person A opening portal) tries to open the portal for Person C, it does not work.

**Comment by hillerstorm** [comment]
> This bug has been partially fixed - https://us.forums.blizzard.com/en/wow/t/cataclysm-dragonwrath-foci-skip-doesnt-do-anything/2013035/8.
> 
> Unfortunately, only the person who actually completed the foci 4-boss event can open the portal successfully and allow others to loot. If Person A (who did the 4-boss event) opens the portal for Person B, then Person B (who skipped the event via Person A opening portal) tries to open the portal for Person C, it does not work.

I'd say it's completely fixed since person B doesn't meet the requirements to open the portal. They only mentioned needing one person to complete that quest, which is now fixed, if you want to be able to open it on another char you have to do that part of the quest.

**Comment by Exesian** [comment]
This issue is fixed so I will be closing this thread, opened #1560 for the discussion regarding letting people who had the portal opened for them also being able to open it for others afterwards.
