### ISSUE TITLE
[BUG] Missing "Create New Profile" Button in Raid Frames Interface

### ISSUE THREAD

**Issue by Bisonpasfute** [ClassicWoWCommunity/cata-classic-bugs#1562]
#### 1.1. Description  
Players are unable to create new raid frame profiles in the Cataclysm client. The option to create new profiles, which should be available in the Raid Profiles interface, is missing entirely. This issue seems to have started with the client changes introduced in the Firelands patch. While the functionality appears to be broken in the interface, it is still possible to create and delete raid profiles using console commands:  
- **To create a new profile:** `/run CreateNewRaidProfile("profilename", "basedonprofile")`  
- **To delete a profile:** `/run DeleteRaidProfile("profile")`  

#### 1.2. How to Reproduce  
1. Open the Raid Profiles menu in the Cataclysm client.  
2. Attempt to locate and use the "Create New Profile" button.  
3. Observe that the button is missing, and new raid profiles cannot be created through the interface.  
4. Use the command `/run CreateNewRaidProfile("profilename", "basedonprofile")` in the chat window to create a new raid profile.  
5. Observe that the command successfully creates a profile, confirming that the functionality exists but is inaccessible via the interface.

#### 1.3. Source Material  
- **Screenshot (Cataclysm):** The Raid Profiles menu showing the missing "Create New Profile" button.  
![image](https://github.com/user-attachments/assets/873152a7-51bf-469e-a472-59c878ebae10)
- **Reddit Thread:** [Can't Create Raid Profile in Interface Options](https://www.reddit.com/r/classicwow/comments/1fynimk/cant_create_raid_profile_in_interface_options/)  
- **Console Commands:**  
  - `/run CreateNewRaidProfile("profilename", "basedonprofile")`  
  - `/run DeleteRaidProfile("profile")`  

#### 2.1. Description  
The Raid Profiles menu should include a "Create New Profile" button that allows players to create and manage additional raid frame profiles directly from the interface. This functionality appears to still exist in the client via console commands and should be restored to the interface for usability.

**Comment by Kethryllia** [comment]
This is also the case in the 1.15.5 client; I'm bugging it both. Thanks!

**Comment by Bisonpasfute** [comment]
Hello @Kethryllia,

It seems that the issue has been addressed !

![image](https://github.com/user-attachments/assets/17d24498-5afb-427b-aa90-6c1cf9beb11d)

I don't know if this is related to this issue or not but thanks !
