### ISSUE TITLE
[BUG] raid info

### ISSUE THREAD

**Issue by SimonBpvp** [ClassicWoWCommunity/cata-classic-bugs#1564]
#### 1.1. Description
this doesn't seem to show you your ID any more, also you can't link it.
  #### 1.2. How to Reproduce

           1. open social 'O'
           2. click Raid Info
           3. try to check your IDs
  #### 1.3  Source Material
![image](https://github.com/user-attachments/assets/43d40039-97b2-4d8d-aa13-6dcb9b2b8461)

#### 2.1. Description
show what boss you killed, and let you link that in chat.
  #### 2.2 Source Material

**Comment by Kethryllia** [comment]
This was previously reported: https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/1371

We have a bug in and will get to it when we can. 🙂
