### ISSUE TITLE
[BUG] No auto attack sound right after a dodge, parry or block

### ISSUE THREAD

**Issue by elrambonator** [ClassicWoWCommunity/cata-classic-bugs#684]
#### 1.1. Description
There is no auto attack sound when the attack happens immediately after you Dodge, Parry or Block. 
I was able to reproduce this with both Warriors and Paladins.
  #### 1.2. How to Reproduce
Easily reproducible with 1 handed weapon + shield or 2 handed weapons:
1. Auto attack target
2. Wait until you counter an attack after you Parry, there is no attack sound.
3. When the attack happens just after you Dodge no sound either.
4. When the attack happens just after a block, no sound either.

Easiest way to reproduce is to fight against a low level mob, since the chances to dodge/parry/block increases greatly. Also helps to not have any other on-hit sounds so it is more noticeable. You'll have fights where no hit makes a single sound because of all the dodges/parries/blocks.
           
  #### 1.3  Source Material
This is the original bug report which states the same info: [no-auto-attack-sound-after-a-dodge-parry-or-block](https://us.forums.blizzard.com/en/wow/t/no-auto-attack-sound-after-a-dodge-parry-or-block/1191364)
#### 2.1. Description
Auto attack hits should make a sound, regardless of other sounds going on.
  #### 2.2 Source Material
This is a video I found of a Paladin during Classic (September 2019) fighting mobs and you can see this exact expected behavior. The timestamp is just before the Paladin makes two consecutive parries and a counter auto attack that makes the corresponding sound: [https://youtu.be/4j0qWyzFyp8?t=3209](https://youtu.be/4j0qWyzFyp8?t=3209)

**Comment by Rowain3** [comment]
Reposted in https://github.com/ClassicWoWCommunity/classic-era-bugs/issues/5
