### ISSUE TITLE
[BUG] You cannot swap weapons/gear while casting (Era/PTR)

### ISSUE THREAD

**Issue by perpabc** [ClassicWoWCommunity/cata-classic-bugs#716]
#### 1.1. Description
You cannot swap weapons/gear while using a spell (also applies to mounts since they're technically spells) with a cast time
  #### 1.2. How to Reproduce

           1. Make a mage
           2. Use frostbolt or any spell with a cast time longer than the GCD
           3. Try to swap weapons/gear (gear while out of combat) during cast
  #### 1.3  Source Material
https://gyazo.com/c843d19288bfd2db541bd7b78adca824
#### 2.1. Description
You should be able to swap weapons/gear while casting something
  #### 2.2 Source Material
https://www.youtube.com/watch?v=GYUbaSCjCTU&t=320s
https://i.imgur.com/sW9zNah.png

**Comment by Rowain3** [comment]
Reposted in https://github.com/ClassicWoWCommunity/classic-era-bugs/issues/7
