### ISSUE TITLE
[BUG] Death Knight Rune recharge visually broken on Mac OS

### ISSUE THREAD

**Issue by Yotsutester** [ClassicWoWCommunity/cata-classic-bugs#891]
#### 1.1. Description
Race: Dwarf
Class: Death Knight
Spec: Blood
Use rune abilities and track how long runes take to recharge. While runes are recharging, using a rune ability will reset the cooldown on other runes. In some cases, despite all runes being available, using a rune ability shortly after all runes have come off cooldown will spend, reset, or place on a short cooldown, other runes that are unrelated to the ability used.
  #### 1.2. How to Reproduce
          1. Attack any mob or target dummy with rune abilities
          2. Observe runes resetting or going on CD after abilities are used
          3. Observe that incorrect runes are being placed on CD
  #### 1.3  Source Material
https://streamable.com/7eg8xu
#### 2.1. Description
Expected behavior: "The new rune system will change how runes regenerate, from filling simultaneously to filling sequentially. For example, if you use two Blood runes, then the first rune will fill up before the second one starts to fill up. Essentially, you have three sets of runes filling every 10 seconds instead of six individual runes filling every 10 seconds. (Haste will cause runes to fill faster.) Another way to think of this is having three runes that go up to 200% each (allowing extra "storage"), rather than six runes that go up to 100% each."
  #### 2.2 Source Material
No source videos as of now

**Comment by CharWS** [comment]
Visual recharge of runes appears to be fixed as of build 4.4.0.54137

**Comment by CharWS** [comment]
seems to still occur under some circumstances as of build 54217

**Comment by Yotsutester** [comment]
Reference Video: https://streamable.com/43vztb

**Comment by fluffs1** [comment]
> seems to still occur under some circumstances as of build 54217 potentially a mac related issue would be curious if any other mac users can re-create the bug, or if any pc users are seeing the issue

Mac user here, can confirm it's bugged for me.
However, it's not a visual bug (visual bugs are when UI displays wrong, but it works correctly), it's just actually bugged.
For me, once in a bugged state, Death Strike consumes anywhere between 2 and 4 death runes.

here's a demo of it bugging out
https://www.youtube.com/watch?v=CtHJ13OLl1M

**Comment by AidanZMoon** [comment]
> > seems to still occur under some circumstances as of build 54217 potentially a mac related issue would be curious if any other mac users can re-create the bug, or if any pc users are seeing the issue
> 
> Mac user here, can confirm it's bugged for me. However, it's not a visual bug (visual bugs are when UI displays wrong, but it works correctly), it's just actually bugged. For me, once in a bugged state, Death Strike consumes anywhere between 2 and 4 death runes.
> 
> here's a demo of it bugging out https://www.youtube.com/watch?v=CtHJ13OLl1M

This is a vosual bug. You are not actually losing any runes.

When you "spend" 4 runes, you actually only have 2 runes. You have all 4 cooldowning down at the same time which should never happen. Each rune set has its own CD. So when you see 4 cooling down at the same time and then spend 4, you actually only have 2 cooling down and are only spending 2.

A visual bug, but a bit annoying. I imagine using rune strike and procing a rune refresh would fix this loop.

**Comment by fluffs1** [comment]
You're right, it's visual. I just remembered something quite vital, that runes regen one at a time in cata, but the visual has monkeybrained me into thinking it didn't change.

Rune strike refresh does not fix it, it actually just makes it look even worse. You can see this happening later on in my clip where the death strike starts (at least visually) using 3 death runes.

**Comment by mikihiso** [comment]
We're entering firelands and this still not fixed.

**Comment by Kethryllia** [comment]
This had some complications since it needed coordination with another team to check it out on the Mac. They're working on getting the bug in though!

**Comment by Kethryllia** [comment]
For the record, it turns out that this affects all ARM64 chips, and the Apple M chips are ARM64. The upshot is that this will also impact Windows machines on ARM64 hardware.

**Comment by Kethryllia** [comment]
This should be fixed in client version 57917.

**Comment by mikihiso** [comment]
You probably meant 57916, yeah - just checked on live, it's now fixed

**Comment by Kethryllia** [comment]
Surely there are Death Knights in a 1.15.5 build, right? >_>

Hehe, thanks, 57916 is the correct version, and I'm glad that it's definitely working now!
